remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Siddhesh Gole]
description: [Results-oriented Procurement Specialist transitioning into Product Management, with 5+ years of experience in streamlining operations, optimizing vendor relationships, and leading cross-functional initiatives. I enjoy building internal tools and B2B solutions that reduce friction, improve data quality, and drive measurable business outcomes.â€‹

ğŸ“ Mumbai, India
ğŸ“§ Email: siddhesh.gole29@gmail.com
ğŸ”— LinkedIn: [www.linkedin.com/in/siddhesh-gole29]
ğŸ“‚ This GitHub: A portfolio of my product thinking, case studies, and PM-focused projects.]
