remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Siddhesh Gole
description: Bridging operational expertise & product vision to build impactful B2B and internal tools. Passionate about user-centered design, data-driven decisions, and agile delivery. Always learning and solving real-world problems.
Location:ğŸ“ Mumbai, India
ğŸ“§ Email: siddhesh.gole29@gmail.com
ğŸ”— LinkedIn: [www.linkedin.com/in/siddhesh-gole29]
ğŸ“‚ This GitHub: A portfolio of my product thinking, case studies, and PM-focused projects.
